name: dorzey.net
markdown: redcarpet
highlighter: pygments
description: dorzey.net - blog posts
url: http://www.dorzey.net
twitter_username: dorzey

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"